spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/jcart?createDatabaseIfNotExist=true
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      - hibernate.format_sql=true